import Car from "../models/car";
import connectDB from "../lib/mongodb";

const carsData = [
  {
    make: "Nissan",
    modelName: "Altima",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 55,
    images: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
    ],
    description:
      "Sleek and sophisticated, the Nissan Altima offers a perfect blend of comfort, technology, and efficiency. Ideal for daily commutes and weekend getaways.",
    features: [
      "Apple CarPlay",
      "Android Auto",
      "Blind Spot Warning",
      "Rear Cross Traffic Alert",
      "Automatic Emergency Braking",
      "Lane Keep Assist",
    ],
    location: "Austin",
    isAvailable: true,
    averageRating: 4.4,
    totalReviews: 92,
    mileage: 12000,
    color: "White",
    licensePlate: "TX-ALT21",
    carType: "Sedan",
  },
  {
    make: "Kia",
    modelName: "Telluride",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 8,
    doors: 4,
    pricePerDay: 95,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "Spacious and luxurious, the Kia Telluride is perfect for large families. Award-winning design with three rows of comfortable seating and premium features.",
    features: [
      "Third Row Seating",
      "Panoramic Sunroof",
      "Harman Kardon Audio",
      "Wireless Charging",
      "Heated and Ventilated Seats",
      "Highway Driving Assist",
      "Surround View Monitor",
    ],
    location: "Orlando",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 145,
    mileage: 8500,
    color: "Dark Blue",
    licensePlate: "FL-2ELL8",
    carType: "SUV",
  },
  {
    make: "Subaru",
    modelName: "Outback",
    year: 2023,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 78,
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    ],
    description:
      "Built for adventure. The Subaru Outback features standard AWD, impressive ground clearance, and rugged capability for any terrain.",
    features: [
      "All-Wheel Drive",
      "EyeSight Safety Suite",
      "Roof Rails",
      "X-Mode Off-Road",
      "Apple CarPlay",
      "Heated Seats",
      "Power Liftgate",
    ],
    location: "Portland",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 118,
    mileage: 24000,
    color: "Forest Green",
    licensePlate: "OR-OUT23",
    carType: "SUV",
  },
  {
    make: "Genesis",
    modelName: "G80",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 140,
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800"],
    description:
      "Korean luxury at its finest. The Genesis G80 delivers Mercedes-level refinement with innovative technology and stunning design.",
    features: [
      "Nappa Leather",
      "Lexicon Audio System",
      "Head-Up Display",
      "Smart Cruise Control",
      "Lane Following Assist",
      "Surround View Camera",
      "Wireless Apple CarPlay",
    ],
    location: "Las Vegas",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 67,
    mileage: 6500,
    color: "Graphite Gray",
    licensePlate: "NV-G80LX",
    carType: "Sedan",
  },
  {
    make: "Tesla",
    modelName: "Model Y",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 7,
    doors: 4,
    pricePerDay: 110,
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800"],
    description:
      "The ultimate electric family SUV. Tesla Model Y offers incredible range, spacious interior with optional third row, and cutting-edge technology.",
    features: [
      "Autopilot",
      "Full Self-Driving Capable",
      "Glass Roof",
      "Premium Interior",
      "Supercharger Access",
      "Over-the-Air Updates",
      "Dog Mode",
    ],
    location: "San Diego",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 203,
    mileage: 15000,
    color: "Midnight Silver",
    licensePlate: "CA-TSLMY",
    carType: "SUV",
  },
  {
    make: "Dodge",
    modelName: "Charger",
    year: 2023,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 105,
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    ],
    description:
      "American muscle sedan with aggressive styling and powerful performance. The Dodge Charger delivers thrills with everyday practicality.",
    features: [
      "Performance Exhaust",
      "Sport Mode",
      "Uconnect System",
      "Apple CarPlay",
      "Alpine Audio",
      "Launch Control",
      "Performance Seats",
    ],
    location: "Las Vegas",
    isAvailable: true,
    averageRating: 4.5,
    totalReviews: 88,
    mileage: 18500,
    color: "Pitch Black",
    licensePlate: "NV-CHRG8",
    carType: "Sedan",
  },
  {
    make: "Volvo",
    modelName: "XC90",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 7,
    doors: 4,
    pricePerDay: 145,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "Swedish luxury and safety combined. The Volvo XC90 Plug-in Hybrid offers three rows of seats, premium Scandinavian design, and excellent fuel economy.",
    features: [
      "Pilot Assist",
      "Bowers & Wilkins Audio",
      "Panoramic Sunroof",
      "Nappa Leather",
      "Heated Steering Wheel",
      "Air Suspension",
      "360 Camera",
      "Massage Seats",
    ],
    location: "Minneapolis",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 76,
    mileage: 9200,
    color: "Crystal White",
    licensePlate: "MN-XC907",
    carType: "SUV",
  },
  {
    make: "Cadillac",
    modelName: "Escalade",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 8,
    doors: 4,
    pricePerDay: 220,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "The ultimate American luxury SUV. Massive presence, three rows of premium seating, and state-of-the-art technology make the Escalade unforgettable.",
    features: [
      "Super Cruise",
      "38-inch Curved OLED Display",
      "AKG Studio Audio",
      "Night Vision",
      "Air Ride Suspension",
      "Rear Entertainment",
      "Wireless Charging",
      "Power Running Boards",
    ],
    location: "Dallas",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 52,
    mileage: 5800,
    color: "Black Raven",
    licensePlate: "TX-ESCLD",
    carType: "SUV",
  },
  {
    make: "Mini",
    modelName: "Cooper S",
    year: 2024,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 4,
    doors: 2,
    pricePerDay: 72,
    images: ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800"],
    description:
      "Fun, zippy, and iconic. The Mini Cooper S is perfect for city driving with its compact size, go-kart handling, and British charm.",
    features: [
      "Sport Mode",
      "Harman Kardon Audio",
      "Heated Seats",
      "Apple CarPlay",
      "LED Headlights",
      "Dual Exhaust",
      "Racing Stripes",
    ],
    location: "San Francisco",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 134,
    mileage: 11200,
    color: "British Racing Green",
    licensePlate: "CA-MINI24",
    carType: "Hatchback",
  },
  {
    make: "Ram",
    modelName: "1500",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Diesel",
    seats: 5,
    doors: 4,
    pricePerDay: 98,
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    ],
    description:
      "Powerful and refined. The Ram 1500 offers best-in-class ride quality, impressive towing capacity, and a luxurious interior.",
    features: [
      "EcoDiesel Engine",
      "12-inch Touchscreen",
      "Air Suspension",
      "Multifunction Tailgate",
      "Panoramic Sunroof",
      "Heated Steering Wheel",
      "Trailer Brake Control",
    ],
    location: "Houston",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 112,
    mileage: 14500,
    color: "Granite Crystal",
    licensePlate: "TX-RAM15",
    carType: "Truck",
  },
  {
    make: "Infiniti",
    modelName: "QX60",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 7,
    doors: 4,
    pricePerDay: 125,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "Elegant three-row luxury SUV with Japanese craftsmanship. The Infiniti QX60 offers quilted leather, smooth ride, and advanced safety features.",
    features: [
      "ProPILOT Assist",
      "Quilted Leather Seats",
      "Bose Audio 17-Speaker",
      "Tri-Zone Climate",
      "Motion Activated Liftgate",
      "Around View Monitor",
      "Wireless Charging",
    ],
    location: "Charlotte",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 81,
    mileage: 10800,
    color: "Majestic White",
    licensePlate: "NC-QX607",
    carType: "SUV",
  },
  {
    make: "Acura",
    modelName: "MDX",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 7,
    doors: 4,
    pricePerDay: 135,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "Premium Japanese SUV with three rows and Super Handling All-Wheel Drive. The MDX Type S delivers performance with luxury and practicality.",
    features: [
      "SH-AWD",
      "ELS Studio 3D Audio",
      "AcuraWatch",
      "Panoramic Moonroof",
      "Heated Second Row",
      "Wireless Charging",
      "Head-Up Display",
    ],
    location: "San Jose",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 94,
    mileage: 8900,
    color: "Apex Blue",
    licensePlate: "CA-MDX24",
    carType: "SUV",
  },
  {
    make: "Alfa Romeo",
    modelName: "Giulia",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 118,
    images: ["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800"],
    description:
      "Italian passion meets performance. The Alfa Romeo Giulia offers stunning design, precise handling, and an engaging driving experience.",
    features: [
      "Sport Mode",
      "Harman Kardon Audio",
      "Leather Sport Seats",
      "Dual-Zone Climate",
      "Apple CarPlay",
      "Active Suspension",
      "Performance Exhaust",
    ],
    location: "Miami",
    isAvailable: true,
    averageRating: 4.5,
    totalReviews: 63,
    mileage: 13400,
    color: "Rosso Red",
    licensePlate: "FL-ALFA9",
    carType: "Sedan",
  },
  {
    make: "Lincoln",
    modelName: "Navigator",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 8,
    doors: 4,
    pricePerDay: 195,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "American luxury at its peak. The Lincoln Navigator offers Presidential-level comfort, advanced technology, and commanding road presence.",
    features: [
      "Perfect Position Seats",
      "Revel Ultima Audio",
      "Massage Function",
      "Rear Entertainment",
      "Wireless Charging Pad",
      "Adaptive Suspension",
      "360 Camera System",
    ],
    location: "Washington DC",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 47,
    mileage: 7200,
    color: "Ceramic Pearl",
    licensePlate: "DC-NAV24",
    carType: "SUV",
  },
  {
    make: "Chrysler",
    modelName: "Pacifica",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 7,
    doors: 4,
    pricePerDay: 88,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "The modern family minivan. Chrysler Pacifica Plug-in Hybrid offers unmatched versatility, Stow 'n Go seating, and impressive fuel economy.",
    features: [
      "Stow 'n Go Seating",
      "Uconnect Theater",
      "Hands-Free Sliding Doors",
      "Tri-Zone Climate",
      "Wireless Charging",
      "Plug-in Hybrid",
      "Vacuum System",
    ],
    location: "Indianapolis",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 156,
    mileage: 19000,
    color: "Velvet Red",
    licensePlate: "IN-PAC24",
    carType: "Van",
  },
  {
    make: "Jaguar",
    modelName: "F-PACE",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 138,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "British luxury SUV with sports car DNA. The F-PACE combines elegant design, dynamic handling, and premium craftsmanship.",
    features: [
      "Meridian Sound System",
      "Windsor Leather",
      "Adaptive Dynamics",
      "Pivi Pro Infotainment",
      "Panoramic Roof",
      "Activity Key",
      "ClearSight Mirror",
    ],
    location: "Boston",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 69,
    mileage: 10500,
    color: "British Racing Green",
    licensePlate: "MA-FPACE",
    carType: "SUV",
  },
  {
    make: "Mazda",
    modelName: "MX-5 Miata",
    year: 2024,
    transmission: "Manual",
    fuelType: "Petrol",
    seats: 2,
    doors: 2,
    pricePerDay: 92,
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    ],
    description:
      "Pure driving joy. The legendary Mazda MX-5 Miata offers open-top thrills, perfect weight balance, and engaging manual transmission.",
    features: [
      "Retractable Soft Top",
      "Bose Audio",
      "Sport-Tuned Suspension",
      "Leather Seats",
      "Bilstein Dampers",
      "Limited Slip Differential",
      "Apple CarPlay",
    ],
    location: "Santa Barbara",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 187,
    mileage: 8300,
    color: "Soul Red Crystal",
    licensePlate: "CA-MX5RF",
    carType: "Convertible",
  },
  {
    make: "GMC",
    modelName: "Yukon",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 8,
    doors: 4,
    pricePerDay: 178,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "Full-size luxury SUV built for families and adventures. The GMC Yukon Denali offers three rows, powerful V8, and premium amenities.",
    features: [
      "Magnetic Ride Control",
      "Bose Premium Audio",
      "Rear Entertainment System",
      "Hands-Free Driving",
      "Power Fold Third Row",
      "Head-Up Display",
      "Adaptive Cruise",
    ],
    location: "Denver",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 91,
    mileage: 12700,
    color: "Onyx Black",
    licensePlate: "CO-YUKON",
    carType: "SUV",
  },
  {
    make: "Buick",
    modelName: "Encore GX",
    year: 2023,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 62,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "Compact luxury on a budget. The Buick Encore GX offers upscale features, quiet cabin, and efficient performance in a small package.",
    features: [
      "QuietTuning",
      "Bose Audio",
      "Wireless Charging",
      "Safety Alert Seat",
      "Apple CarPlay",
      "Remote Start",
      "Power Liftgate",
    ],
    location: "Pittsburgh",
    isAvailable: true,
    averageRating: 4.4,
    totalReviews: 105,
    mileage: 21000,
    color: "Summit White",
    licensePlate: "PA-ENCO2",
    carType: "SUV",
  },
  {
    make: "Lamborghini",
    modelName: "Huracan",
    year: 2023,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 2,
    doors: 2,
    pricePerDay: 850,
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
    ],
    description:
      "Italian supercar excellence. The Lamborghini Huracan delivers breathtaking performance, exotic looks, and an unforgettable driving experience.",
    features: [
      "V10 Engine",
      "Launch Control",
      "Carbon Ceramic Brakes",
      "Anima Drive Modes",
      "Alcantara Interior",
      "Variable Steering",
      "Performance Exhaust",
    ],
    location: "Miami",
    isAvailable: false,
    averageRating: 5.0,
    totalReviews: 28,
    mileage: 3200,
    color: "Arancio Borealis",
    licensePlate: "FL-LAMBO",
    carType: "Sports",
  },
  {
    make: "Rivian",
    modelName: "R1T",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    doors: 4,
    pricePerDay: 155,
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    ],
    description:
      "Electric adventure truck. The Rivian R1T combines zero-emission driving with serious off-road capability and innovative features like the gear tunnel.",
    features: [
      "Quad Motor AWD",
      "Camp Kitchen",
      "Gear Tunnel Storage",
      "Air Suspension",
      "Tank Turn",
      "Underbody Armor",
      "15.6-inch Touchscreen",
    ],
    location: "Seattle",
    isAvailable: true,
    averageRating: 4.8,
    totalReviews: 74,
    mileage: 9800,
    color: "Compass Yellow",
    licensePlate: "WA-RIV1T",
    carType: "Truck",
  },
  {
    make: "Lucid",
    modelName: "Air",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    doors: 4,
    pricePerDay: 175,
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800"],
    description:
      "The future of luxury EVs. Lucid Air offers over 500 miles of range, stunning design, and a spacious, tech-forward interior.",
    features: [
      "Dreamdrive Pro",
      "Glass Canopy Roof",
      "Surreal Sound Audio",
      "Ambient Lighting",
      "Executive Rear Seats",
      "Curved 34-inch Display",
      "500+ Mile Range",
    ],
    location: "Los Angeles",
    isAvailable: true,
    averageRating: 4.9,
    totalReviews: 42,
    mileage: 4600,
    color: "Stellar White",
    licensePlate: "CA-LUCID",
    carType: "Sedan",
  },
  {
    make: "Polestar",
    modelName: "2",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Electric",
    seats: 5,
    doors: 4,
    pricePerDay: 89,
    images: ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800"],
    description:
      "Swedish electric performance. Polestar 2 offers Google-powered infotainment, minimalist Scandinavian design, and engaging driving dynamics.",
    features: [
      "Google Built-In",
      "Pixel LED Headlights",
      "Pilot Assist",
      "Harman Kardon Audio",
      "Vegan Interior Option",
      "Phone as Key",
      "Heat Pump",
    ],
    location: "San Francisco",
    isAvailable: true,
    averageRating: 4.6,
    totalReviews: 118,
    mileage: 11900,
    color: "Thunder",
    licensePlate: "CA-PSTR2",
    carType: "Hatchback",
  },
  {
    make: "Maserati",
    modelName: "Levante",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Petrol",
    seats: 5,
    doors: 4,
    pricePerDay: 210,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "Italian luxury SUV with a racing pedigree. The Maserati Levante combines exotic styling, powerful engines, and handcrafted interior.",
    features: [
      "Bowers & Wilkins Audio",
      "Nerissimo Carbon Fiber",
      "Pieno Fiore Leather",
      "Skyhook Suspension",
      "Sport Exhaust",
      "Heated Rear Seats",
      "Hands-Free Liftgate",
    ],
    location: "Scottsdale",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 55,
    mileage: 8100,
    color: "Blu Emozione",
    licensePlate: "AZ-MASER",
    carType: "SUV",
  },
  {
    make: "Toyota",
    modelName: "Sienna",
    year: 2024,
    transmission: "Automatic",
    fuelType: "Hybrid",
    seats: 8,
    doors: 4,
    pricePerDay: 92,
    images: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
    ],
    description:
      "The hybrid family van. Toyota Sienna offers all-wheel drive, exceptional fuel economy, and flexible seating for up to 8 passengers.",
    features: [
      "AWD Hybrid",
      "Super Long Slide Seats",
      "Built-in Vacuum",
      "Rear Entertainment",
      "Tri-Zone Climate",
      "Safety Sense 2.5",
      "Power Sliding Doors",
    ],
    location: "Sacramento",
    isAvailable: true,
    averageRating: 4.7,
    totalReviews: 167,
    mileage: 16500,
    color: "Blueprint",
    licensePlate: "CA-SIEN8",
    carType: "Van",
  },
];

async function seedCars() {
  try {
    console.log("🔌 Connecting to MongoDB...");
    await connectDB();

    console.log("🗑️  Clearing existing cars...");
    //  await Car.deleteMany({});

    console.log("🌱 Seeding cars...");
    const createdCars = await Car.insertMany(carsData);

    console.log(`✅ Successfully seeded ${createdCars.length} cars!`);
    console.log("\nSample cars created:");
    createdCars.forEach((car, index) => {
      console.log(
        `${index + 1}. ${car.year} ${car.make} ${car.modelName} - $${
          car.pricePerDay
        }/day (${car.location})`
      );
    });

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seedCars();
